apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: canary-replicaset
spec:
  replicas: 1
  selector:
    matchLabels:
      app: config-reader
      version: canary
  template:
    metadata:
      labels:
        app: config-reader
        version: canary
    spec:
      containers:
        - name: nginx
          image: nginx:alpine
          volumeMounts:
            - name: config-volume
              mountPath: /usr/share/nginx/html
              readOnly: true
      volumes:
        - name: config-volume
          configMap:
            name: canary-config
            
