apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: config-reader
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  selector:
    matchLabels:
      app: config-reader
  template:
    metadata:
      labels:
        app: config-reader
  volumes:
    - name: config-volume
      configMap:
        name: config-reader-stable-config
  strategy:
    canary:
      stableService: config-reader-stable
      canaryService: config-reader-canary
      steps:
        - setWeight: 0
        - pause: {}
      trafficRouting:
        istio:
          virtualService:
            name: config-reader-virtual-service
            routes:
              - primary 