apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

namePrefix: canary-

patches:
  - path: rollout-patch.yaml
    target:
      kind: Rollout
      name: config-reader-base 