apiVersion: apps/v1
kind: Deployment
metadata:
  name: pod-template
spec:
  template:
    metadata:
      labels:
        app: config-reader
    spec:
      containers:
        - name: nginx
          image: nginx:alpine
          volumeMounts:
            - name: config-volume
              mountPath: /usr/share/nginx/html
              readOnly: true
